app/mod_client/models.py
from app import db
from datetime import datetime
import random 
import string
import time

from app import app
from flask_sqlalchemy import SQLAlchemy, BaseQuery


  
# defining function for random 
# string id with parameter

from search import add_to_index, remove_from_index, query_index
'''
class SearchableMixin(object):
    @classmethod
    def search(cls, expression, page, per_page):
        ids, total = query_index(cls.__tablename__, expression, page, per_page)
        if total == 0:
            return cls.query.filter_by(id=0), 0
        when = []
        for i in range(len(ids)):
            when.append((ids[i], i))
        return cls.query.filter(cls.id.in_(ids)).order_by(
            db.case(when, value=cls.id)), total

    @classmethod
    def before_commit(cls, session):
        session._changes = {
            'add': list(session.new),
            'update': list(session.dirty),
            'delete': list(session.deleted)
        }

    @classmethod
    def after_commit(cls, session):
        for obj in session._changes['add']:
            if isinstance(obj, SearchableMixin):
                add_to_index(obj.__tablename__, obj)
        for obj in session._changes['update']:
            if isinstance(obj, SearchableMixin):
                add_to_index(obj.__tablename__, obj)
        for obj in session._changes['delete']:
            if isinstance(obj, SearchableMixin):
                remove_from_index(obj.__tablename__, obj)
        session._changes = None

    @classmethod
    def reindex(cls):
        for obj in cls.query:
            add_to_index(cls.__tablename__, obj)

db.event.listen(db.session, 'before_commit', SearchableMixin.before_commit)
db.event.listen(db.session, 'after_commit', SearchableMixin.after_commit)


def ran_gen(size, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for x in range(size)) 



# Define a base model for other database tables to inherit
class Base(db.Model):

    __abstract__  = True

    id            = db.Column(db.Integer, primary_key=True)
    date_created  = db.Column(db.DateTime,  default=db.func.current_timestamp())
    date_modified = db.Column(db.DateTime,  default=db.func.current_timestamp(),
                                           onupdate=db.func.current_timestamp())

# Define a User model
class Client(Base,SearchableMixin):
    __tablename__ = 'client'
    __searchable__ = ['org_name']
    # User Name
    org_name    = db.Column(db.String(128),  nullable=False)# Identification Data: email & password
    website    = db.Column(db.String(128),  nullable=False)
    clientID  = db.Column(db.String(128), nullable=False,unique=True)
    phoneNumber = db.Column(db.String(128), nullable=False)
    address1 = db.Column(db.String(128), nullable=False)
    address2 = db.Column(db.String(128), nullable=False)
    city = db.Column(db.String(128), nullable=False)
    state = db.Column(db.String(128), nullable=False)
    country = db.Column(db.String(128), nullable=False)


    # New instance instantiation procedure
    def __init__(self, org_name, website, phoneNumber,address1,address2,city,state,country,clientID):

        self.org_name     = org_name
        self.website    = website
        self.clientID = str(int(time.time()))
        self.phoneNumber = phoneNumber
        self.address1 = address1
        self.address2 = address2
        self.city = city
        self.state = state
        self.country = country

        

    def __repr__(self):
        return '<Client %r>' % (self.org_name)

class Contact(Base,SearchableMixin):
    __tablename__ = 'contact'
    __searchable__ = ['name','organisationName']
    # User Name
    name    = db.Column(db.String(128),  nullable=False)# Identification Data: email & password
    linkedIN    = db.Column(db.String(128),  nullable=False)
    organisationID  = db.Column(db.Integer , nullable=False)
    organisationName = db.Column(db.String(128), nullable=False)
    contactID = db.Column(db.String(128), nullable=False, unique=True)
    phoneNumber = db.Column(db.String(128), nullable=False)
    email = db.Column(db.String(128), nullable=False)
    position = db.Column(db.String(128), nullable=False)


    # New instance instantiation procedure
    def __init__(self, name, linkedIN, email,phoneNumber,orgID,orgName,position,contactID):

        self.name   = name
        self.linkedIN    = linkedIN
        self.organisationID = orgID
        self.organisationName = orgName
        self.contactID = contactID
        self.phoneNumber = phoneNumber
        self.email = email
        self.position = position

        

    def __repr__(self):
        return '<Client %r>' % (self.name)


db.create_all()
'''

app/mod_client/controllers.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for,jsonify

# Import password / encryption helper tools
from werkzeug import check_password_hash, generate_password_hash

# Import the database object from the main app module
from app import db

import time
from sqlalchemy import literal
import json

import jsonpickle


# Import module models (i.e. User)
#from app.mod_client.models import Client
#from app.mod_client.models import Contact

#from app.mod_client.sample_data import sampleClientList

# Define the blueprint: 'auth', set its url prefix: app.url/auth

mod_client = Blueprint('client', __name__, url_prefix='/client')


"""et the route and accepted methods

@mod_auth.route('/signin/', methods=['GET', 'POST'])
def signin():

    # If sign in form is submitted
    form = LoginForm(request.form)

    # Verify the sign in form
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user and check_password_hash(user.password, form.password.data):

            session['user_id'] = user.id

            flash('Welcome %s' % user.name)

            return redirect(url_for('auth.home'))

        flash('Wrong email or password', 'error-message')

    return render_template("auth/signin.html", form=form)







@mod_client.route('/create', methods=['GET', 'POST'])
def addClient():
    print("Got the hit")
    id = int(time.time())
    return render_template("mod_client/AddClients.html", id=id)


@mod_client.route('/contact/create', methods=['GET', 'POST'])
def addContact():
    print("Got the hit")
    id = int(time.time())
    return render_template("mod_client/AddContact.html", id=id)

@mod_client.route('/detail/<int:id>/', methods=['GET','POST'])
def detailPage(id):
    print("Got hit on the detailPage")
    client = Client.query.get(id)
    return render_template("mod_client/ClientDetail.html", client=client)

@mod_client.route('/contact-detail/<int:id>/', methods=['GET','POST'])
def contact_Detail(id):
    print("Got hit on the detailPage")
    contact = Contact.query.get(id)
    return render_template("mod_client/ContactDetail.html", client=contact)


@mod_client.route('/browse/<int:pnum>/', methods=['GET','POST'])
def browseClients(pnum):
    if(request.method == "GET"):
        print("Got the hit after redirection -its a get request")
    if(session.get('client_searchSetStatus')):
        print("Session is search set, return search result")
        print(session['clientsearch_startDate'], session['clientsearch_query'])
    print("proceeding",request)
    record_query = Client.query.paginate(pnum, 10, False)
    total = record_query.total
    print(record_query, "total")
    clients = Client.query.all()
    totalpages = (len(clients)//10 +1)
    print("totalpages", totalpages)
    return render_template("mod_client/BrowseClients.html", clientList= record_query.items,len = len(record_query.items),pnum =pnum,totalpages=totalpages)

@mod_client.route('/browse-contact/<int:pnum>/', methods=['GET','POST'])
def browseContacts(pnum):
    if(request.method == "GET"):
        print("Got the hit after redirection -its a get request")
    if(session.get('client_searchSetStatus')):
        print("Session is search set, return search result")
        print(session['clientsearch_startDate'], session['clientsearch_query'])
    print("proceeding",request)
    record_query = Contact.query.paginate(pnum, 10, False)
    total = record_query.total
    print(record_query, "total")
    contacts = Contact.query.all()
    totalpages = (len(contacts)//10 +1)
    print("totalpages", totalpages)
    return render_template("mod_client/BrowseContacts.html", contactList= record_query.items,len = len(record_query.items),pnum =pnum,totalpages=totalpages)


def obj_dict(obj):
    return obj.__dict__

class ClientURL:
  def __init__(self, name, id,country):
    self.name = name
    self.id = id
    self.country = country

@mod_client.route('/api/v1.0/search/', methods=['GET'])
def getSearch():
    searchTerm = request.args.get('q')
    print("searchTerm",searchTerm)
    query, total = Client.search(searchTerm, 1, 5)
    print(query.all())
    resp = []
    for item in query.all():
        ret = ClientURL(item.org_name,item.id,item.country)
        #ret = item.org_name
        print(ret,"searchResultitem")
        resp.append(ret)
    return jsonpickle.encode(resp,unpicklable=False)

@mod_client.route('/api/v1.0/create', methods=['POST'])
def create_task():
    #print(request.get_data())
    request_json     = request.json
    print("Got the hit",request_json)
    #session.get('logged_in') == True:  {'name': 'sdss', 'city': 
    #'sd', 'vat': 'sdsd', 'country': 'India', 'clientID': ' 1575541447', 
    #'state': 'sd', 'address2': 'sd', 'address1': 'sd', 'site': 'sdsd.ci'}
    # def __init__(self, name, website, phoneNumber,address1,address2,city,state,country):
    name = request_json['name']
    city = request_json['city']
    vat = request_json['vat']
    country = request_json['country']
    clientID = request_json['clientID']
    state = request_json['state']
    address1 = request_json['address1']
    address2 = request_json['address2']
    site = request_json['site']
    clientID = request_json['clientID']
    phoneNumber = 123456
    client = Client(org_name = name, website=site,phoneNumber= phoneNumber, address1=address1, address2=address2,city=city,state=state,country=country,clientID=clientID)
    db.session.add(client)
    db.session.commit()
    resp = jsonify(success=True)
    resp.status_code = 200
    return resp

@mod_client.route('/api/v1.0/setSearch', methods=['POST'])
def set_search():
    #print(request.get_data())
    request_json     = request.json
    print("Got the hit",request_json)
    resp = jsonify(success=True)
    resp.status_code = 200
    #print(sess)
    session['client_searchSetStatus'] = 1
    session['clientsearch_startDate'] = request_json['start']
    session['clientsearch_endDate'] = request_json['end']
    session['clientsearch_query'] = request_json['query']
    print(session['clientsearch_query'])
    #return redirect(url_for('client.list', pnum = 2),code=302)
    #return redirect(url_for('client.test'),code=302)
    resp = jsonify(success=True)
    return resp

@mod_client.route('/api/v1.0/addcontact', methods=['POST'])
def create_contact():
    #print(request.get_data())
    #{'position': 'sdsd', 'companyID': 13, 'linkedInURL': 'sds.com', 'company': 'MES logistics', 
    #'contactID': ' 1575758286', 'email': 'sd@sd.com', 'name': 'sdsd'}
    request_json     = request.json
    position = request_json['position']
    companyID = request_json['companyID']
    linkedInURL = request_json['linkedInURL']
    company = request_json['company']
    contactID = request_json['contactID']
    email = request_json['email']
    name = request_json['name']
    # def __init__(self, name, linkedIN, email,phoneNumber,orgID,orgName,position,contactID):
    contact = Contact(name = name, linkedIN=linkedInURL,email= email,phoneNumber= 12345678, orgID=companyID, orgName=company, position=position,contactID=contactID )
    db.session.add(contact)
    db.session.commit()
    resp = jsonify(success=True)
    resp.status_code = 200
    return resp

"""

app/templates/mod_client/BrowseClients.html
<!DOCTYPE html>
<html lang="en">

    {% include "/assets.html" %}

    {% block body %}
        <script src="/static/assets/js/waves.min.js"></script>

        <!-- Begin page -->
        <div id="wrapper">

            <!-- Top Bar Start -->
    		{% include "/topnav.html" %}
            <!-- Top Bar End -->

            <!-- ========== Left Sidebar Start ========== -->
            {% include "/sidebar.html" %}
            <!-- Left Sidebar End -->

            <!-- ============================================================== -->
            <!-- Start right Content here #30419B-->
            <!-- ============================================================== -->
            <style>
            #customers {
              font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
              border-collapse: collapse;
              width: 80%;
              margin-left: 10%;
              margin-right: 10%;
              margin-top: 15px;
            }

            .loader {
              border: 16px solid #f3f3f3; /* Light grey */
              border-top: 16px solid #3498db; /* Blue */
              border-radius: 50%;
              width: 120px;
              height: 120px;
              margin-left: 40%;
              margin-right: 10%;
              animation: spin 2s linear infinite;
            }

            @keyframes spin {
              0% { transform: rotate(0deg); }
              100% { transform: rotate(360deg); }
            }	
            
            .center {
              margin: auto;
              width: auto;
              padding-top: 15px;
              text-align: center;
              
            }
            .center2 {
              
              margin-left: 10%;
              margin-right: 10%;

              
              text-align: center;
              
              
            }

            #customers td, #customers th {
              border: 1px solid #ddd;
              padding: 8px;
            }

            #customers tr:nth-child(even){background-color: #f2f2f2;}

            #customers tr:hover {background-color: #ddd;}

            #customers th {
              padding-top: 12px;
              padding-bottom: 12px;
              text-align: left;
              background-color: #30419B;
              color: white;
            }
            </style>
            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container-fluid">
                        <div class="page-title-box" style="margin:auto; padding-bottom: 0px;">
                            <h4 class="mt-0 header-title">VIEW CLIENTS</h4>
                            <p class="sub-title">View and Query All the Clients in Database</p>
                         </div>
                        <!-- end page-title -->
                        <!--  -->
                        <div class="row center2">
                        	<div class="col-lg-3" style="position: block;">
                        		<label style="display: inline-block;">Search</label>
                        		<input class="form-control" type="search" value="" id="searchtab">
                        		
                        	</div>
                        	<div class="col-lg-3">
                        		<label>From</label>
                        		<input class="form-control" type="date" value="" id="begin-date">
                        	</div>
                        	<div class="col-lg-3">
                        		<label>To</label>
                        		<input class="form-control" type="date" value="" id="end-date">
                        	</div>
                        	<div class="col-lg-3 center">
                        		<button type="button" class="btn btn-warning" id="searchBtn" >Search</button>
                        		<button type="button" class="btn btn-warning" id="searchBtn" >Clear</button>
                        	</div>
                        	

                        </div>

                        <div class="row" id="tableRow">
                        	<div id="loadHolder" class="center">
                        	</div>
                        	<table id="customers">
                        	  <tr class="click-row">
                        	    <th>Company</th>
                        	    <th>Country</th>
                        	    <th>City</th>
                        	  </tr>
                        	  
                        	  {%for i in range(0, len)%}

                        	  	<tr class="click-row">
                        	  	  <td><a href = "{{ url_for('client.detailPage', id=clientList[i].id) }}">{{clientList[i].org_name}}</td>
                        	  	  <td>{{clientList[i].country}}</td>
                        	  	  <td>{{clientList[i].city}}</td>
                        	  	</tr> 
                        	     
                        	  {%endfor%} 
                        	</table>
                        </div>
                        <div class="row center" id="paginationHolder">
                        	<nav aria-label="..." class="center">
                        	    <ul class="pagination" id="paginator" >
                        	        
                        	        <!--
									<li class="page-item disabled">
									    <a class="page-link" href="#" tabindex="-1">Previous</a>
									</li>
                        	        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        	        <li class="page-item active">
                        	            <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                        	        </li>
                        	        <li class="page-item"><a class="page-link" href="#">3</a></li>
									<li class="page-item">
									    <a class="page-link" href="#">Next</a>
									</li>

                        	    -->
                        	        
                        	    </ul>
                        	</nav>
                        </div>
                        
                    </div>
                    <!-- container-fluid -->

                </div>
                <!-- content -->

                

            </div>


                <!-- content -->



            </div>
            <!-- ============================================================== -->
            <!-- End Right content here -->
            <!-- ============================================================== -->

        <!-- END wrapper -->


        
    {% endblock %}
    {% include "/jsassets.html" %}
    <script type="text/javascript">
        $(document).ready(function() {

        	/*
			<div class="row" id="loader">
                        	<div class="loader"></div>
             </div>

			<li class="page-item disabled">
			    <a class="page-link" href="#" tabindex="-1">Previous</a>
			</li>
			<li class="page-item">

			<a class="page-link" href="#">Next</a>
									</li>
        	*/
        	var pnum = {{pnum}};
        	var tnum = {{totalpages}};
        	console.log(pnum,tnum);
        	var pagesDisplayed = 0;

        	if(tnum >10){

        		pagesDisplayed = 10;
        	}else{

        		pagesDisplayed = tnum;
        	}

        	$('#paginator').append('<li class="page-item disabled"><a class="page-link" href="#" tabindex="-1">Previous</a></li>');

        	/*
			<li class="page-item active">
                        	            <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                        	        </li>
        	*/

        	for (i = 0; i < tnum; i++) {
        	  if(i+1 != pnum){
        	  	$('#paginator').append('<li class="page-item"><a class="page-link" href="/client/browse/'+(i+1)+'">'+(i+1)+'</a></li>');
        	  }else{
        	  	$('#paginator').append('<li class="page-item active"><a class="page-link" href="/client/browse/'+(i+1)+'">'+(i+1)+'<span class="sr-only">(current)</span></a></li>');
        	  }
        	  

        	}

        	$('#paginator').append('<li class="page-item"><a class="page-link" href="#">Next</a></li>');

        	$("#customers").on('click-row.bs.table', function (e, row, $element) {
        	    window.location = $element.data('href');
        	});

        	$('#searchBtn').on('click', function(event){

        		$("#loadHolder").append('<div class="loader"></div>');
        		$("#customers").hide();
        		$("#paginationHolder").hide();

        		var query = $('#searchtab').val();
        		var begin_date = $('#begin-date').val();
        		var end_date = $('#end-date').val();

        		if (query != null && begin_date != null && end_date != null){


        		

        		$.ajax({
        		    data : JSON.stringify( { "query": query, "start": begin_date,"end":end_date } ),
        		    type : 'POST',
        		    dataType: 'json',
        		    contentType: 'application/json',
        		    url : '/client/api/v1.0/setSearch'
        		})
        		.done(function(data) {

        			$(location).attr('href', '/client/browse/1/');
        			console.log("successful post");

        		    if (data.error) {
        		        console.log(data.error)
        		    }
        		    else {
        		        console.log("excellent")
        		        $(location).attr('href', '/client/browse/1/')

        		    }

        		});
        	}
        	else{

        		alert("Give the query properly, Boss!")
        	}

        		//$("#customers").hide();


        	});

        });
        
    </script>

    
</html>

app/templates/mod_client/BrowseContacts.html
<!DOCTYPE html>
<html lang="en">

    {% include "/assets.html" %}

    {% block body %}
        <script src="/static/assets/js/waves.min.js"></script>

        <!-- Begin page -->
        <div id="wrapper">

            <!-- Top Bar Start -->
    		{% include "/topnav.html" %}
            <!-- Top Bar End -->

            <!-- ========== Left Sidebar Start ========== -->
            {% include "/sidebar.html" %}
            <!-- Left Sidebar End -->

            <!-- ============================================================== -->
            <!-- Start right Content here #30419B-->
            <!-- ============================================================== -->
            <style>
            #customers {
              font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
              border-collapse: collapse;
              width: 80%;
              margin-left: 10%;
              margin-right: 10%;
              margin-top: 15px;
            }

            .loader {
              border: 16px solid #f3f3f3; /* Light grey */
              border-top: 16px solid #3498db; /* Blue */
              border-radius: 50%;
              width: 120px;
              height: 120px;
              margin-left: 40%;
              margin-right: 10%;
              animation: spin 2s linear infinite;
            }

            @keyframes spin {
              0% { transform: rotate(0deg); }
              100% { transform: rotate(360deg); }
            }	
            
            .center {
              margin: auto;
              width: auto;
              padding-top: 15px;
              text-align: center;
              
            }
            .center2 {
              
              margin-left: 10%;
              margin-right: 10%;

              
              text-align: center;
              
              
            }

            #customers td, #customers th {
              border: 1px solid #ddd;
              padding: 8px;
            }

            #customers tr:nth-child(even){background-color: #f2f2f2;}

            #customers tr:hover {background-color: #ddd;}

            #customers th {
              padding-top: 12px;
              padding-bottom: 12px;
              text-align: left;
              background-color: #30419B;
              color: white;
            }
            </style>
            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container-fluid">
                        <div class="page-title-box" style="margin:auto; padding-bottom: 0px;">
                            <h4 class="mt-0 header-title">VIEW CLIENTS</h4>
                            <p class="sub-title">View and Query All the Clients in Database</p>
                         </div>
                        <!-- end page-title -->
                        <!--  -->
                        <div class="row center2">
                        	<div class="col-lg-3" style="position: block;">
                        		<label style="display: inline-block;">Search</label>
                        		<input class="form-control" type="search" value="" id="searchtab">
                        		
                        	</div>
                        	<div class="col-lg-3">
                        		<label>From</label>
                        		<input class="form-control" type="date" value="" id="begin-date">
                        	</div>
                        	<div class="col-lg-3">
                        		<label>To</label>
                        		<input class="form-control" type="date" value="" id="end-date">
                        	</div>
                        	<div class="col-lg-3 center">
                        		<button type="button" class="btn btn-warning" id="searchBtn" >Search</button>
                        		<button type="button" class="btn btn-warning" id="searchBtn" >Clear</button>
                        	</div>
                        	

                        </div>

                        <div class="row" id="tableRow">
                        	<div id="loadHolder" class="center">
                        	</div>
                        	<table id="customers">
                        	  <tr class="click-row">
                        	    <th>Company</th>
                        	    <th>Country</th>
                        	    <th>City</th>
                        	  </tr>
                        	  
                        	  {%for i in range(0, len)%}

                        	  	<tr class="click-row">
                        	  	  <td><a href = "{{ url_for('client.contact_Detail', id=contactList[i].id) }}">{{contactList[i].name}}</td>
                        	  	  <td>{{contactList[i].organisationName}}</td>
                        	  	  <td>{{contactList[i].position}}</td>
                        	  	</tr> 
                        	     
                        	  {%endfor%} 
                        	</table>
                        </div>
                        <div class="row center" id="paginationHolder">
                        	<nav aria-label="..." class="center">
                        	    <ul class="pagination" id="paginator" >
                        	        
                        	        <!--
									<li class="page-item disabled">
									    <a class="page-link" href="#" tabindex="-1">Previous</a>
									</li>
                        	        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        	        <li class="page-item active">
                        	            <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                        	        </li>
                        	        <li class="page-item"><a class="page-link" href="#">3</a></li>
									<li class="page-item">
									    <a class="page-link" href="#">Next</a>
									</li>

                        	    -->
                        	        
                        	    </ul>
                        	</nav>
                        </div>
                        
                    </div>
                    <!-- container-fluid -->

                </div>
                <!-- content -->

                

            </div>


                <!-- content -->



            </div>
            <!-- ============================================================== -->
            <!-- End Right content here -->
            <!-- ============================================================== -->

        <!-- END wrapper -->


        
    {% endblock %}
    {% include "/jsassets.html" %}
    <script type="text/javascript">
        $(document).ready(function() {

        	/*
			<div class="row" id="loader">
                        	<div class="loader"></div>
             </div>

			<li class="page-item disabled">
			    <a class="page-link" href="#" tabindex="-1">Previous</a>
			</li>
			<li class="page-item">

			<a class="page-link" href="#">Next</a>
									</li>
        	*/
        	var pnum = {{pnum}};
        	var tnum = {{totalpages}};
        	console.log(pnum,tnum);
        	var pagesDisplayed = 0;

        	if(tnum >10){

        		pagesDisplayed = 10;
        	}else{

        		pagesDisplayed = tnum;
        	}

        	$('#paginator').append('<li class="page-item disabled"><a class="page-link" href="#" tabindex="-1">Previous</a></li>');

        	/*
			<li class="page-item active">
                        	            <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                        	        </li>
        	*/

        	for (i = 0; i < tnum; i++) {
        	  if(i+1 != pnum){
        	  	$('#paginator').append('<li class="page-item"><a class="page-link" href="/client/browse/'+(i+1)+'">'+(i+1)+'</a></li>');
        	  }else{
        	  	$('#paginator').append('<li class="page-item active"><a class="page-link" href="/client/browse/'+(i+1)+'">'+(i+1)+'<span class="sr-only">(current)</span></a></li>');
        	  }
        	  

        	}

        	$('#paginator').append('<li class="page-item"><a class="page-link" href="#">Next</a></li>');

        	$("#customers").on('click-row.bs.table', function (e, row, $element) {
        	    window.location = $element.data('href');
        	});

        	$('#searchBtn').on('click', function(event){

        		$("#loadHolder").append('<div class="loader"></div>');
        		$("#customers").hide();
        		$("#paginationHolder").hide();

        		var query = $('#searchtab').val();
        		var begin_date = $('#begin-date').val();
        		var end_date = $('#end-date').val();

        		if (query != null && begin_date != null && end_date != null){


        		

        		$.ajax({
        		    data : JSON.stringify( { "query": query, "start": begin_date,"end":end_date } ),
        		    type : 'POST',
        		    dataType: 'json',
        		    contentType: 'application/json',
        		    url : '/client/api/v1.0/setSearch'
        		})
        		.done(function(data) {

        			$(location).attr('href', '/client/browse/1/');
        			console.log("successful post");

        		    if (data.error) {
        		        console.log(data.error)
        		    }
        		    else {
        		        console.log("excellent")
        		        $(location).attr('href', '/client/browse/1/')

        		    }

        		});
        	}
        	else{

        		alert("Give the query properly, Boss!")
        	}

        		//$("#customers").hide();


        	});

        });
        
    </script>

    
</html>